# Generated by Django 2.0.7 on 2018-07-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTitle', models.TextField()),
                ('client', models.TextField()),
                ('division', models.TextField()),
                ('category', models.TextField()),
                ('status', models.TextField()),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('entryForm', models.FileField(upload_to='submissions/')),
                ('summary', models.FileField(upload_to='submissions/')),
                ('file1', models.FileField(upload_to='submissions/')),
                ('file2', models.FileField(upload_to='submissions/')),
                ('file3', models.FileField(upload_to='submissions/')),
                ('links', models.URLField()),
            ],
        ),
    ]
